apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  client-id: kuberde-server-admin
  client-secret: ${KEYCLOAK_CLIENT_SECRET_FOR_SERVER}
