---
# 主域名和 SSO 的 Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuberde-server-ingress
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: ${KUBERDE_PUBLIC_DOMAIN},${KEYCLOAK_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  rules:
  - host: ${KUBERDE_PUBLIC_DOMAIN}
    http:
      paths:
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: kuberde-server
            port:
              number: 8080
      - path: /connect
        pathType: Prefix
        backend:
          service:
            name: kuberde-server
            port:
              number: 8080
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: kuberde-server
            port:
              number: 8080
      - path: /mgmt
        pathType: Prefix
        backend:
          service:
            name: kuberde-server
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: kuberde-server
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuberde-web
            port:
              number: 80
  - host: ${KEYCLOAK_DOMAIN}
    http:
      paths:
      - path: /realms
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
      - path: /resources
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
      - path: /robots.txt
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
  - host: "*.${KUBERDE_AGENT_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuberde-server
            port:
              number: 8080
  tls:
  - hosts:
    - ${KUBERDE_PUBLIC_DOMAIN}
    - "*.${KUBERDE_PUBLIC_DOMAIN}"
  - hosts:
    - ${KEYCLOAK_DOMAIN}