{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuberde.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "kuberde.web.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: {{ .Values.web.service.port }}
    name: http
    protocol: TCP
{{- end }}
