{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuberde.fullname" . }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.service.type }}
  selector:
    {{- include "kuberde.keycloak.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.keycloak.service.port }}
    targetPort: {{ .Values.keycloak.service.port }}
    name: http
    protocol: TCP
{{- end }}
