{{- if .Values.secrets.create }}
{{- if not .Values.secrets.existingSecrets.keycloakAgentClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-agent-client-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLIENT_ID: {{ .Values.secrets.keycloakClients.agentClientId | quote }}
  CLIENT_SECRET: {{ .Values.secrets.keycloakClients.agentClientSecret | quote }}
{{- end }}
{{- end }}
