{{- if .Values.secrets.create }}
{{- if not .Values.secrets.existingSecrets.keycloakAdminClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-client-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.secrets.keycloakClients.serverClientId }}
  client-secret: {{ .Values.secrets.keycloakClients.serverClientSecret | quote }}
{{- end }}
{{- end }}
