{{- if .Values.postgresql.enabled }}
{{- if .Values.secrets.create }}
{{- if not .Values.secrets.existingSecrets.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.database.name | quote }}
  POSTGRES_USER: {{ .Values.secrets.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.database.password | quote }}
{{- end }}
{{- end }}
{{- end }}
