{{- if .Values.server.enabled }}
{{- if .Values.server.rbac.create }}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "kuberde.fullname" . }}-server-binding
  labels:
    {{- include "kuberde.server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kuberde.fullname" . }}-server-role
subjects:
- kind: ServiceAccount
  name: {{ include "kuberde.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
