{{- if .Values.server.enabled }}
{{- if .Values.server.rbac.create }}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ include "kuberde.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kuberde.fullname" . }}-server
subjects:
- kind: ServiceAccount
  name: {{ include "kuberde.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
