{{- if .Values.server.enabled }}
{{- if .Values.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kuberde.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.server.labels" . | nindent 4 }}
  {{- with .Values.server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
