{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuberde.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuberde.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "kuberde.server.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.service.port }}
    name: http
    protocol: TCP
{{- end }}
